# Generated by Django 3.0.8 on 2020-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30, verbose_name='time')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='humidity')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='temperature')),
            ],
        ),
    ]
